
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Tbl Facilities      <small><?= cclang('detail', ['Tbl Facilities']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/tbl_facilities'); ?>">Tbl Facilities</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Tbl Facilities</h3>
                     <h5 class="widget-user-desc">Detail Tbl Facilities</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tbl_facilities" id="form_tbl_facilities" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_facilities->id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Title </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_facilities->title); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Venue Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_facilities->title); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">No Of Inventories </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_facilities->no_of_inventories); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Min Players </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_facilities->min_players); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Max Players </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_facilities->max_players); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Default Players </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_facilities->default_players); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Price Per Slot </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_facilities->price_per_slot); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Opening Time </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_facilities->opening_time); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Closing Time </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_facilities->closing_time); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Available 24 Hours </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_facilities->available_24_hours); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Slot Length Hrs </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_facilities->slot_length_hrs); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Slot Length Min </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_facilities->slot_length_min); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Slot Frequency </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_facilities->slot_frequency); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Activity </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_facilities->activity); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status </label>

                        <div class="col-sm-8">
                           <?php if($tbl_facilities->status == '1'){ echo 'Active'; }else{ echo 'Inactive'; } ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('tbl_facilities_update', function() use ($tbl_facilities){?>
                        <?php $crnt_url_id =  basename(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH)); ?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit tbl_facilities (Ctrl+e)" href="<?= site_url('administrator/tbl_facilities/edit/'.$crnt_url_id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Tbl Facilities']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/tbl_facilities/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Tbl Facilities']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
