
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Tbl_facilities/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Tbl Facilities<small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Tbl Facilities</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('tbl_facilities_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', ['Tbl Facilities']); ?>  (Ctrl+a)" href="<?=  site_url('administrator/tbl_facilities/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', ['Tbl Facilities']); ?></a>
                        <?php }) ?>
                        <?php is_allowed('tbl_facilities_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> Tbl Facilities" href="<?= site_url('administrator/tbl_facilities/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('tbl_facilities_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf Tbl Facilities" href="<?= site_url('administrator/tbl_facilities/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Tbl Facilities</h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', ['Tbl Facilities']); ?>  <i class="label bg-yellow"><?= $tbl_facilities_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_tbl_facilities" id="form_tbl_facilities" action="<?= base_url('administrator/tbl_facilities/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                           <th>Title</th>
                           <th>Venue Id</th>
                           <th>No Of Inventories</th>
                           <th>Min Players</th>
                           <th>Max Players</th>
                           <th>Default Players</th>
                           <th>Price Per Slot</th>
                           <th>Opening Time</th>
                           <th>Closing Time</th>
                           <th>Available 24 Hours</th>
                           <th>Slot Length Hrs</th>
                           <th>Slot Length Min</th>
                           <th>Slot Frequency</th>
                           <th>Activity</th>
                           <th>Status</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_tbl_facilities">
                     <?php foreach($tbl_facilitiess as $tbl_facilities): ?>
                        <tr>
                           <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $tbl_facilities->id; ?>">
                           </td>
                           
                           <td><?= _ent($tbl_facilities->title); ?></td> 
                           <td><?= _ent($tbl_facilities->title); ?></td>
                             
                           <td><?= _ent($tbl_facilities->no_of_inventories); ?></td> 
                           <td><?= _ent($tbl_facilities->min_players); ?></td> 
                           <td><?= _ent($tbl_facilities->max_players); ?></td> 
                           <td><?= _ent($tbl_facilities->default_players); ?></td> 
                           <td><?= _ent($tbl_facilities->price_per_slot); ?></td> 
                           <td><?= _ent($tbl_facilities->opening_time); ?></td> 
                           <td><?= _ent($tbl_facilities->closing_time); ?></td> 
                           <td><?= _ent($tbl_facilities->available_24_hours); ?></td> 
                           <td><?= _ent($tbl_facilities->slot_length_hrs); ?></td> 
                           <td><?= _ent($tbl_facilities->slot_length_min); ?></td> 
                           <td><?= _ent($tbl_facilities->slot_frequency); ?></td> 
                           <td><?= _ent($tbl_facilities->activity); ?></td> 
                           <td><?php if($tbl_facilities->status == '1'){ echo 'Active'; }else{ echo 'Inactive'; } ?></td> 
                           <td width="200">
                              <?php is_allowed('tbl_facilities_view', function() use ($tbl_facilities){?>
                              <a href="<?= site_url('administrator/tbl_facilities/view/' . $tbl_facilities->id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                              <?php is_allowed('tbl_facilities_update', function() use ($tbl_facilities){?>
                              <a href="<?= site_url('administrator/tbl_facilities/edit/' . $tbl_facilities->id); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('tbl_facilities_delete', function() use ($tbl_facilities){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/tbl_facilities/delete/' . $tbl_facilities->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($tbl_facilities_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Tbl Facilities data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                           <option value="delete">Delete</option>
                        </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'title' ? 'selected' :''; ?> value="title">Title</option>
                           <option <?= $this->input->get('f') == 'venue_id' ? 'selected' :''; ?> value="venue_id">Venue Id</option>
                           <option <?= $this->input->get('f') == 'no_of_inventories' ? 'selected' :''; ?> value="no_of_inventories">No Of Inventories</option>
                           <option <?= $this->input->get('f') == 'min_players' ? 'selected' :''; ?> value="min_players">Min Players</option>
                           <option <?= $this->input->get('f') == 'max_players' ? 'selected' :''; ?> value="max_players">Max Players</option>
                           <option <?= $this->input->get('f') == 'default_players' ? 'selected' :''; ?> value="default_players">Default Players</option>
                           <option <?= $this->input->get('f') == 'price_per_slot' ? 'selected' :''; ?> value="price_per_slot">Price Per Slot</option>
                           <option <?= $this->input->get('f') == 'opening_time' ? 'selected' :''; ?> value="opening_time">Opening Time</option>
                           <option <?= $this->input->get('f') == 'closing_time' ? 'selected' :''; ?> value="closing_time">Closing Time</option>
                           <option <?= $this->input->get('f') == 'available_24_hours' ? 'selected' :''; ?> value="available_24_hours">Available 24 Hours</option>
                           <option <?= $this->input->get('f') == 'slot_length_hrs' ? 'selected' :''; ?> value="slot_length_hrs">Slot Length Hrs</option>
                           <option <?= $this->input->get('f') == 'slot_length_min' ? 'selected' :''; ?> value="slot_length_min">Slot Length Min</option>
                           <option <?= $this->input->get('f') == 'slot_frequency' ? 'selected' :''; ?> value="slot_frequency">Slot Frequency</option>
                           <option <?= $this->input->get('f') == 'activity' ? 'selected' :''; ?> value="activity">Activity</option>
                           <option <?= $this->input->get('f') == 'status' ? 'selected' :''; ?> value="status">Status</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/tbl_facilities');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_tbl_facilities').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/tbl_facilities/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>