
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      User Subscription      <small><?= cclang('detail', ['User Subscription']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/tbl_user_subscription'); ?>">User Subscription</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">User Subscription</h3>
                     <h5 class="widget-user-desc">Detail User Subscription</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tbl_user_subscription" id="form_tbl_user_subscription" >
                    
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pass Type </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_user_subscription->title); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Rewards </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_user_subscription->rewards); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sports </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_user_subscription->sport_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Validity </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_user_subscription->validity); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Show Policy </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_user_subscription->show_policy); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Advance Booking </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_user_subscription->advance_booking); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Max Play Time </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_user_subscription->max_play_time); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Max Player </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_user_subscription->max_player); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Applicable On </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_user_subscription->applicable_on); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Note </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_user_subscription->notes); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_user_subscription->status==1)?'Active':'Inactive'; ?>
                        </div>
                    </div>        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('tbl_user_subscription_update', function() use ($tbl_user_subscription){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit tbl_user_subscription (Ctrl+e)" href="<?= site_url('administrator/tbl_user_subscription/edit/'.$tbl_user_subscription->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Tbl User Subscription']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/tbl_user_subscription/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Tbl User Subscription']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
