
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Tbl Venue      <small><?= cclang('detail', ['Tbl Venue']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/tbl_venue'); ?>">Tbl Venue</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Tbl Venue</h3>
                     <h5 class="widget-user-desc">Detail Tbl Venue</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tbl_venue" id="form_tbl_venue" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_venue->id); ?>
                        </div>
                    </div>
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">User Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_venue->email); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Image </label>
                        <div class="col-sm-8">
                             <?php if (is_image($tbl_venue->image)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/tbl_venue/' . $tbl_venue->image; ?>">
                                <img src="<?= BASE_URL . 'uploads/tbl_venue/' . $tbl_venue->image; ?>" class="image-responsive" alt="image tbl_venue" title="image tbl_venue" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/tbl_venue/' . $tbl_venue->image; ?>">
                                 <img src="<?= get_icon_file($tbl_venue->image); ?>" class="image-responsive" alt="image tbl_venue" title="image <?= $tbl_venue->image; ?>" width="40px"> 
                               <?= $tbl_venue->image ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Title </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_venue->title); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sports </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_venue->sport_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Amenities </label>
                        <div class="col-sm-8">
                           <?= _ent($tbl_venue->name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Description </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_venue->description); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Address </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_venue->address); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Address Map </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_venue->address_map); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Latitude </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_venue->latitude); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Longitude </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_venue->longitude); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Video Url </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_venue->video_url); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status </label>

                        <div class="col-sm-8">
                           <?php if($tbl_venue->status == '1'){ echo 'Active'; }else{ echo 'Inactive'; } ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('tbl_venue_update', function() use ($tbl_venue){?>
                        <?php $crnt_url_id =  basename(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH)); ?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit tbl_venue (Ctrl+e)" href="<?= site_url('administrator/tbl_venue/edit/'.$crnt_url_id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Tbl Venue']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/tbl_venue/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Tbl Venue']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
