
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Tbl Tournament1      <small><?= cclang('detail', ['Tbl Tournament1']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/tbl_tournament1'); ?>">Tbl Tournament1</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Tbl Tournament1</h3>
                     <h5 class="widget-user-desc">Detail Tbl Tournament1</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tbl_tournament1" id="form_tbl_tournament1" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_tournament1->id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">User Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_tournament1->name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Academy Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_tournament1->name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Title </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_tournament1->title); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">No Of Tickets </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_tournament1->no_of_tickets); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Tickets Left </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_tournament1->tickets_left); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Price </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_tournament1->price); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Start Date </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_tournament1->start_date); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">End Date </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_tournament1->end_date); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Description </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_tournament1->description); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Type </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_tournament1->type); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Image </label>
                        <div class="col-sm-8">
                             <?php if (is_image($tbl_tournament1->image)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/tbl_tournament1/' . $tbl_tournament1->image; ?>">
                                <img src="<?= BASE_URL . 'uploads/tbl_tournament1/' . $tbl_tournament1->image; ?>" class="image-responsive" alt="image tbl_tournament1" title="image tbl_tournament1" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/tbl_tournament1/' . $tbl_tournament1->image; ?>">
                                 <img src="<?= get_icon_file($tbl_tournament1->image); ?>" class="image-responsive" alt="image tbl_tournament1" title="image <?= $tbl_tournament1->image; ?>" width="40px"> 
                               <?= $tbl_tournament1->image ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Url </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_tournament1->url); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Approved </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_tournament1->approved); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sponsors </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_tournament1->sponsors); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Latitude </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_tournament1->latitude); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Longitude </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_tournament1->longitude); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Address </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_tournament1->address); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_tournament1->status); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Created At </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_tournament1->created_at); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Updated At </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_tournament1->updated_at); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('tbl_tournament1_update', function() use ($tbl_tournament1){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit tbl_tournament1 (Ctrl+e)" href="<?= site_url('administrator/tbl_tournament1/edit/'.$tbl_tournament1->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Tbl Tournament1']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/tbl_tournament1/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Tbl Tournament1']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
