
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Orders      <small><?= cclang('detail', ['Orders']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/tbl_orders'); ?>">Orders</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Orders</h3>
                     <h5 class="widget-user-desc">Detail Orders</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tbl_orders" id="form_tbl_orders" >
                   
                    <div class="row">

                     <div class="col-md-6">
                           <div class="form-group ">
                              <label for="content" class="col-sm-2 control-label">User</label>

                              <div class="col-sm-8">
                                 <a href="<?=base_url('administrator/tbl_user/view/').$tbl_orders->user_id;?>"><?= GetUserInfo($tbl_orders->user_id)->name; ?></a>
                              </div>
                          </div>
                                               
                          <div class="form-group ">
                              <label for="content" class="col-sm-2 control-label">Partner</label>

                              <div class="col-sm-8">
                                 <a href="<?=base_url('administrator/tbl_user/view/').$tbl_orders->partner_id;?>"><?= GetUserInfo($tbl_orders->partner_id)->name; ?></a>
                              </div>
                          </div>

                          <?php
                              $type = $tbl_orders->type;
                              if($type==1){
                                 $typename = "Facility Booking";
                              }elseif($type==2){
                                 $typename = "Academy Session booking";
                              }elseif($type==3){
                                 $typename = "Tournament Booking";
                              }else{
                                 $typename = "";
                              }

                              
                              $status = $tbl_orders->status;
                              if($status==1){
                                 $statusvalue = "Complete";
                              }elseif($status==2){
                                 $statusvalue = "Pending";
                              }elseif($status==3){
                                 $statusvalue = "Failed";
                              }else{
                                 $statusvalue = "";
                              }
                           
                           ?>
                                               
                          <div class="form-group ">
                              <label for="content" class="col-sm-2 control-label">Type </label>

                              <div class="col-sm-8">
                                 <?= $typename; ?>
                              </div>
                          </div>

                          <div class="form-group ">
                              <label for="content" class="col-sm-2 control-label">Order Date </label>

                              <div class="col-sm-8">
                                 <?= $tbl_orders->order_date; ?>
                              </div>
                          </div>
                                               
                          
                                               
                          <div class="form-group ">
                              <label for="content" class="col-sm-2 control-label">Transaction Id </label>

                              <div class="col-sm-8">
                                 <?= _ent($tbl_orders->transaction_id); ?>
                              </div>
                          </div>
                                               
                          <div class="form-group ">
                              <label for="content" class="col-sm-2 control-label">Status </label>

                              <div class="col-sm-8">
                                 <?= $statusvalue; ?>
                              </div>
                          </div>
                                               
                          <div class="form-group ">
                              <label for="content" class="col-sm-2 control-label">Created At </label>

                              <div class="col-sm-8">
                                 <?= _ent($tbl_orders->created_at); ?>
                              </div>
                          </div>
                                               
                          <div class="form-group ">
                              <label for="content" class="col-sm-2 control-label">Updated At </label>

                              <div class="col-sm-8">
                                 <?= _ent($tbl_orders->updated_at); ?>
                              </div>
                          </div>

                             
                     </div>

                     <div class="col-md-6">
                        <h3>Order Detail</h3>
                        <h4>Order Type : <?=$typename;?></h4>
                           <?php if($tbl_orders->type==1) {?>
                              <!-- Facility booking -->
                              <div class="form-group ">
                                 <label for="content" class="col-sm-2 control-label">Facility Title </label>

                                 <div class="col-sm-8">
                                    <a target="_blank" href="<?=base_url('administrator/tbl_facilities/view/').$tbl_orders->order_detail->facility_detail->id?>"><?= $tbl_orders->order_detail->facility_detail->title ?? ""; ?></a>
                                 </div>
                              </div>

                             <div class="form-group ">
                                 <label for="content" class="col-sm-2 control-label">Date </label>

                                 <div class="col-sm-8">
                                    <?= $tbl_orders->order_detail->date ?? ""; ?>
                                 </div>
                             </div> 

                             <div class="form-group ">
                                 <label for="content" class="col-sm-2 control-label">Slot Start Time </label>

                                 <div class="col-sm-8">
                                    <?= $tbl_orders->order_detail->slot_start_time ?? ""; ?>
                                 </div>
                             </div> 

                             <div class="form-group ">
                                 <label for="content" class="col-sm-2 control-label">Slot End Time </label>

                                 <div class="col-sm-8">
                                    <?= $tbl_orders->order_detail->slot_end_time ?? ""; ?>
                                 </div>
                             </div> 


                          <?php } ?>

                          <?php if($tbl_orders->type==2) {?>
                              <!-- Session booking -->
                              <div class="form-group ">
                                 <label for="content" class="col-sm-2 control-label">Session Title </label>

                                 <div class="col-sm-8">
                                    <a target="_blank" href="<?=base_url('administrator/tbl_sessions/view/').$tbl_orders->order_detail->id?>"><?= $tbl_orders->order_detail->title ?? ""; ?></a>
                                 </div>
                              </div>

                             <div class="form-group ">
                                 <label for="content" class="col-sm-2 control-label">Academy Name </label>

                                 <div class="col-sm-8">
                                    <a target="_blank" href="<?=base_url('administrator/tbl_academy/view/').$tbl_orders->order_detail->academy_id?>"><?= GetTableInfo($tbl_orders->order_detail->academy_id,'tbl_academy')->name ?? ""; ?></a>
                                 </div>
                             </div> 

                          <?php } ?>

                          <?php if($tbl_orders->type==3) {?>
                              <!-- Tournament booking -->
                              <div class="form-group ">
                                 <label for="content" class="col-sm-2 control-label">Tournament Title </label>

                                 <div class="col-sm-8">
                                    <a target="_blank" href="<?=base_url('administrator/tbl_tournament/view/').$tbl_orders->order_detail->id?>"><?= $tbl_orders->order_detail->title ?? ""; ?></a>
                                 </div>
                              </div>

                             <div class="form-group ">
                                 <label for="content" class="col-sm-2 control-label">Academy Name </label>

                                 <div class="col-sm-8">
                                    <a target="_blank" href="<?=base_url('administrator/tbl_academy/view/').$tbl_orders->order_detail->academy_id?>"><?= GetTableInfo($tbl_orders->order_detail->academy_id,'tbl_academy')->name ?? ""; ?></a>
                                 </div>
                             </div> 

                             <div class="form-group ">
                                 <label for="content" class="col-sm-2 control-label"> Start Date </label>

                                 <div class="col-sm-8">
                                    <?= $tbl_orders->order_detail->start_date ?? ""; ?>
                                 </div>
                             </div> 

                             <div class="form-group ">
                                 <label for="content" class="col-sm-2 control-label">End Date </label>

                                 <div class="col-sm-8">
                                    <?= $tbl_orders->order_detail->end_date ?? ""; ?>
                                 </div>
                             </div> 

                             <?php
                             if($tbl_orders->order_detail->type==2){ ?>
                              <div class="form-group ">
                                 <label for="content" class="col-sm-2 control-label">URL </label>

                                 <div class="col-sm-8">
                                    <?= $tbl_orders->order_detail->url ?? ""; ?>
                                 </div>
                             </div> 
                             <?php }
                             
                             } ?>


                          <h3>Transaction Detail</h3>
                              <div class="form-group ">
                                 <label for="content" class="col-sm-2 control-label">Amount </label>

                                 <div class="col-sm-8">
                                    <?= $transaction_data->amount ?? ""; ?>
                                 </div>
                             </div>

                             <div class="form-group ">
                                 <label for="content" class="col-sm-2 control-label">Transaction Id </label>

                                 <div class="col-sm-8">
                                    <?= $transaction_data->transaction_id ?? ""; ?>
                                 </div>
                             </div>

                             <div class="form-group ">
                                 <label for="content" class="col-sm-2 control-label">Transaction Status </label>

                                 <div class="col-sm-8">
                                    <?= $transaction_data->payment_status ?? ""; ?>
                                 </div>
                             </div> 



                     </div>
                    </div>
                                         
                    

                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('tbl_orders_update', function() use ($tbl_orders){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit tbl_orders (Ctrl+e)" href="<?= site_url('administrator/tbl_orders/edit/'.$tbl_orders->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Tbl Orders']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/tbl_orders/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Tbl Orders']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
