
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Sports      <small><?= cclang('detail', ['Sports']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/tbl_sports'); ?>">Sports</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Sports</h3>
                     <h5 class="widget-user-desc">Detail Sports</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tbl_sports" id="form_tbl_sports" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sport Name </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_sports->sport_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Sport Icon </label>
                        <div class="col-sm-8">
                             <?php if (is_image($tbl_sports->sport_icon)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/tbl_sports/' . $tbl_sports->sport_icon; ?>">
                                <img src="<?= BASE_URL . 'uploads/tbl_sports/' . $tbl_sports->sport_icon; ?>" class="image-responsive" alt="image tbl_sports" title="sport_icon tbl_sports" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/tbl_sports/' . $tbl_sports->sport_icon; ?>">
                                 <img src="<?= get_icon_file($tbl_sports->sport_icon); ?>" class="image-responsive" alt="image tbl_sports" title="sport_icon <?= $tbl_sports->sport_icon; ?>" width="40px"> 
                               <?= $tbl_sports->sport_icon ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sport Price </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_sports->sport_price); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status </label>

                        <div class="col-sm-8">
                           <?php if($tbl_sports->status == 1){ echo 'Active'; }else{ echo 'Inactive'; } ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('tbl_sports_update', function() use ($tbl_sports){?>
                        <?php $crnt_url_id =  basename(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH)); ?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit tbl_sports (Ctrl+e)" href="<?= site_url('administrator/tbl_sports/edit/'.$crnt_url_id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Tbl Sports']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/tbl_sports/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Tbl Sports']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
