
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Tbl_academy/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Tbl Academy<small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Tbl Academy</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('tbl_academy_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', ['Tbl Academy']); ?>  (Ctrl+a)" href="<?=  site_url('administrator/tbl_academy/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', ['Tbl Academy']); ?></a>
                        <?php }) ?>
                        <?php is_allowed('tbl_academy_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> Tbl Academy" href="<?= site_url('administrator/tbl_academy/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('tbl_academy_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf Tbl Academy" href="<?= site_url('administrator/tbl_academy/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Tbl Academy</h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', ['Tbl Academy']); ?>  <i class="label bg-yellow"><?= $tbl_academy_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_tbl_academy" id="form_tbl_academy" action="<?= base_url('administrator/tbl_academy/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                           <th>Address</th>
                           <th>Logo</th>
                           <th>Latitude</th>
                           <th>Longitude</th>
                           <th>Contact No</th>
                           <th>Head Coach</th>
                           <th>Session Timings</th>
                           <th>Week Days</th>
                           <th>Price</th>                           
                           <th>Status</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_tbl_academy">
                     <?php foreach($tbl_academys as $tbl_academy): ?>
                        <tr>
                           <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $tbl_academy->id; ?>">
                           </td>
                             
                           <td><?= _ent($tbl_academy->address); ?></td> 
                           <td>
                              <?php if (!empty($tbl_academy->logo)): ?>
                                <?php if (is_image($tbl_academy->logo)): ?>
                                <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/tbl_academy/' . $tbl_academy->logo; ?>">
                                  <img src="<?= BASE_URL . 'uploads/tbl_academy/' . $tbl_academy->logo; ?>" class="image-responsive" alt="image tbl_academy" title="logo tbl_academy" width="40px">
                                </a>
                                <?php else: ?>
                                  <a href="<?= BASE_URL . 'administrator/file/download/tbl_academy/' . $tbl_academy->logo; ?>">
                                   <img src="<?= get_icon_file($tbl_academy->logo); ?>" class="image-responsive image-icon" alt="image tbl_academy" title="logo <?= $tbl_academy->logo; ?>" width="40px"> 
                                 </a>
                                <?php endif; ?>
                              <?php endif; ?>
                           </td>
                            
                           <td><?= _ent($tbl_academy->latitude); ?></td> 
                           <td><?= _ent($tbl_academy->longitude); ?></td> 
                           <td><?= _ent($tbl_academy->contact_no); ?></td> 
                           <td><?= _ent($tbl_academy->head_coach); ?></td> 
                           <td><?= _ent($tbl_academy->session_timings); ?></td> 
                           <td><?= _ent($tbl_academy->week_days); ?></td> 
                           <td><?= _ent($tbl_academy->price); ?></td> 
                           <td><?php if($tbl_academy->status == '1'){ echo 'Active'; }else{ echo 'Inactive'; } ?></td> 
                           <td width="200">
                              <?php is_allowed('tbl_academy_view', function() use ($tbl_academy){?>
                              <a href="<?= site_url('administrator/tbl_academy/view/' . $tbl_academy->id); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                              <?php is_allowed('tbl_academy_update', function() use ($tbl_academy){?>
                              <a href="<?= site_url('administrator/tbl_academy/edit/' . $tbl_academy->id); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('tbl_academy_delete', function() use ($tbl_academy){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/tbl_academy/delete/' . $tbl_academy->id); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($tbl_academy_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Tbl Academy data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                           <option value="delete">Delete</option>
                        </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'user_id' ? 'selected' :''; ?> value="user_id">User Id</option>
                           <option <?= $this->input->get('f') == 'venue_id' ? 'selected' :''; ?> value="venue_id">Venue Id</option>
                           <option <?= $this->input->get('f') == 'name' ? 'selected' :''; ?> value="name">Name</option>
                           <option <?= $this->input->get('f') == 'address' ? 'selected' :''; ?> value="address">Address</option>
                           <option <?= $this->input->get('f') == 'logo' ? 'selected' :''; ?> value="logo">Logo</option>
                           <option <?= $this->input->get('f') == 'latitude' ? 'selected' :''; ?> value="latitude">Latitude</option>
                           <option <?= $this->input->get('f') == 'longitude' ? 'selected' :''; ?> value="longitude">Longitude</option>
                           <option <?= $this->input->get('f') == 'description' ? 'selected' :''; ?> value="description">Description</option>
                           <option <?= $this->input->get('f') == 'contact_no' ? 'selected' :''; ?> value="contact_no">Contact No</option>
                           <option <?= $this->input->get('f') == 'head_coach' ? 'selected' :''; ?> value="head_coach">Head Coach</option>
                           <option <?= $this->input->get('f') == 'session_timings' ? 'selected' :''; ?> value="session_timings">Session Timings</option>
                           <option <?= $this->input->get('f') == 'week_days' ? 'selected' :''; ?> value="week_days">Week Days</option>
                           <option <?= $this->input->get('f') == 'price' ? 'selected' :''; ?> value="price">Price</option>
                           <option <?= $this->input->get('f') == 'remarks_price' ? 'selected' :''; ?> value="remarks_price">Remarks Price</option>
                           <option <?= $this->input->get('f') == 'skill_level' ? 'selected' :''; ?> value="skill_level">Skill Level</option>
                           <option <?= $this->input->get('f') == 'academy_jersey' ? 'selected' :''; ?> value="academy_jersey">Academy Jersey</option>
                           <option <?= $this->input->get('f') == 'capacity' ? 'selected' :''; ?> value="capacity">Capacity</option>
                           <option <?= $this->input->get('f') == 'remarks_current_capacity' ? 'selected' :''; ?> value="remarks_current_capacity">Remarks Current Capacity</option>
                           <option <?= $this->input->get('f') == 'session_plan' ? 'selected' :''; ?> value="session_plan">Session Plan</option>
                           <option <?= $this->input->get('f') == 'remarks_session_plan' ? 'selected' :''; ?> value="remarks_session_plan">Remarks Session Plan</option>
                           <option <?= $this->input->get('f') == 'age_group_of_students' ? 'selected' :''; ?> value="age_group_of_students">Age Group Of Students</option>
                           <option <?= $this->input->get('f') == 'remarks_students' ? 'selected' :''; ?> value="remarks_students">Remarks Students</option>
                           <option <?= $this->input->get('f') == 'equipment' ? 'selected' :''; ?> value="equipment">Equipment</option>
                           <option <?= $this->input->get('f') == 'remarks_on_equipment' ? 'selected' :''; ?> value="remarks_on_equipment">Remarks On Equipment</option>
                           <option <?= $this->input->get('f') == 'flood_lights' ? 'selected' :''; ?> value="flood_lights">Flood Lights</option>
                           <option <?= $this->input->get('f') == 'ground_size' ? 'selected' :''; ?> value="ground_size">Ground Size</option>
                           <option <?= $this->input->get('f') == 'person' ? 'selected' :''; ?> value="person">Person</option>
                           <option <?= $this->input->get('f') == 'coach_experience' ? 'selected' :''; ?> value="coach_experience">Coach Experience</option>
                           <option <?= $this->input->get('f') == 'no_of_assistent_coach' ? 'selected' :''; ?> value="no_of_assistent_coach">No Of Assistent Coach</option>
                           <option <?= $this->input->get('f') == 'assistent_coach_name' ? 'selected' :''; ?> value="assistent_coach_name">Assistent Coach Name</option>
                           <option <?= $this->input->get('f') == 'feedbacks' ? 'selected' :''; ?> value="feedbacks">Feedbacks</option>
                           <option <?= $this->input->get('f') == 'amenities_id' ? 'selected' :''; ?> value="amenities_id">Amenities Id</option>
                           <option <?= $this->input->get('f') == 'sports' ? 'selected' :''; ?> value="sports">Sports</option>
                           <option <?= $this->input->get('f') == 'status' ? 'selected' :''; ?> value="status">Status</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/tbl_academy');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_tbl_academy').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/tbl_academy/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>