
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Tbl Academy      <small><?= cclang('detail', ['Tbl Academy']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/tbl_academy'); ?>">Tbl Academy</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Tbl Academy</h3>
                     <h5 class="widget-user-desc">Detail Tbl Academy</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tbl_academy" id="form_tbl_academy" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">User Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->email); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Venue Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->title); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Name </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Address </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->address); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> Logo </label>
                        <div class="col-sm-8">
                             <?php if (is_image($tbl_academy->logo)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/tbl_academy/' . $tbl_academy->logo; ?>">
                                <img src="<?= BASE_URL . 'uploads/tbl_academy/' . $tbl_academy->logo; ?>" class="image-responsive" alt="image tbl_academy" title="logo tbl_academy" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/tbl_academy/' . $tbl_academy->logo; ?>">
                                 <img src="<?= get_icon_file($tbl_academy->logo); ?>" class="image-responsive" alt="image tbl_academy" title="logo <?= $tbl_academy->logo; ?>" width="40px"> 
                               <?= $tbl_academy->logo ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Latitude </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->latitude); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Longitude </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->longitude); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Description </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->description); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Contact No </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->contact_no); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Head Coach </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->head_coach); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Session Timings </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->session_timings); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Week Days </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->week_days); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Price </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->price); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Remarks Price </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->remarks_price); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Skill Level </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->skill_level); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Academy Jersey </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->academy_jersey); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Capacity </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->capacity); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Remarks Current Capacity </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->remarks_current_capacity); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Session Plan </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->session_plan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Remarks Session Plan </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->remarks_session_plan); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Age Group Of Students </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->age_group_of_students); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Remarks Students </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->remarks_students); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Equipment </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->equipment); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Remarks On Equipment </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->remarks_on_equipment); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Flood Lights </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->flood_lights); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Ground Size </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->ground_size); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Person </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->person); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Coach Experience </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->coach_experience); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">No Of Assistant Coach </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->no_of_assistent_coach); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Assistant Coach Name </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->assistent_coach_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Feedbacks </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->feedbacks); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Amenities Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Sports </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_academy->sport_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status </label>

                        <div class="col-sm-8">
                           <?php if($tbl_academy->status == '1'){ echo 'Active'; }else{ echo 'Inactive'; } ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('tbl_academy_update', function() use ($tbl_academy){?>
                        <?php $crnt_url_id =  basename(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH)); ?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit tbl_academy (Ctrl+e)" href="<?= site_url('administrator/tbl_academy/edit/'.$crnt_url_id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Tbl Academy']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/tbl_academy/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Tbl Academy']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
