
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Cms Pages      <small><?= cclang('detail', ['Cms Pages']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/tbl_cms_pages'); ?>">Cms Pages</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Cms Pages</h3>
                     <h5 class="widget-user-desc">Detail Cms Pages</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_tbl_cms_pages" id="form_tbl_cms_pages" >
                   
                    <!-- <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Id </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_cms_pages->id); ?>
                        </div>
                    </div> -->
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Slug </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_cms_pages->slug); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Title </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_cms_pages->title); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Description </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_cms_pages->description); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status </label>

                        <div class="col-sm-8">
                           <?= ($tbl_cms_pages->status==1)?'Active':'Inactive' ?>
                        </div>
                    </div>
                                         
                    <!-- <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Created At </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_cms_pages->created_at); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Updated At </label>

                        <div class="col-sm-8">
                           <?= _ent($tbl_cms_pages->updated_at); ?>
                        </div>
                    </div> -->
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('tbl_cms_pages_update', function() use ($tbl_cms_pages){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit tbl_cms_pages (Ctrl+e)" href="<?= site_url('administrator/tbl_cms_pages/edit/'.$tbl_cms_pages->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Cms Pages']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/tbl_cms_pages/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Cms Pages']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
